create table TA_CATALOG (
    id integer not null generated always as identity (start with 1, increment by 1),
    bundleId varchar(255) not null,
    bundleVersionMajor integer not null,
    bundleVersionMinor integer not null,
    bundleVersionPatch integer not null,
    bundleVersionLabel varchar(128) not null,
    bundleVersionReleaseBuild boolean not null,
    bundleName varchar(255) not null,
    bundleDescription varchar(16384) not null,
    bundleUrl varchar(2048) not null,
    bundleClass varchar(255) not null,
    viewrekaVersionMajor integer not null,
    viewrekaVersionMinor integer not null,
    viewrekaVersionPatch integer not null,
    categories varchar(1024) not null,
    homePage varchar(2048) not null,
    ownerId varchar(255) not null,
    ownerScreenName varchar(255) not null,
    ownerService varchar(255) not null,
    ownerProfileUrl varchar(2000) not null,
    createTime BIGINT not null,
    lastUpdateTime bigint not null,
    constraint PK_CATALOG primary key (id),
    constraint U_CATALOG unique(bundleId, bundleVersionMajor, bundleVersionMinor, bundleVersionPatch, bundleVersionLabel, bundleVersionReleaseBuild)
);
